<?php

require_once (dirname(__FILE__) . '/../../../TestBootstrap.php');

/**
 * Test class for ZendX_View_Autoescape
 * Generated by PHPUnit on 2011-09-09 at 22:42:56.
 */
class ZendX_View_Facade_StringTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var ZendX_View_Autoescape
     */
    protected $_view;

    public function __construct($name = NULL, array $data = array(), $dataName = '')
    {
        parent::__construct($name, $data, $dataName);
        
        $this->_view = new ZendX_View_Autoescape();
    }


    protected function setUp()
    {
        $this->_view->clearVars();
    }

    /**
     * encoding of this file ist important for successful testing
     */
    public function testHtmlEscapingContextForStringTypes()
    {
        $testObject = new ZendX_View_Facade_String('Hallo <Jens> gib mal €s', $this->_view);
        
        $this->assertEquals('Hallo &lt;Jens&gt; gib mal €s', (string) $testObject);
        $this->assertInstanceOf('ZendX_View_Facade_String', $testObject->html());
        $this->assertEquals('Hallo <Jens> gib mal €s', (string) $testObject->nofilter());
        $this->assertEquals('Hallo <Jens> gib mal €s', (string) $testObject->raw());
        $this->assertEquals('Hallo &lt;Jens&gt; gib mal €s', (string) $testObject->html());
        $this->assertEquals('"Hallo <Jens> gib mal \u20acs"', (string) $testObject->json());
        
    }
    
}
